### PR TITLE
 links to introduction + other DMOTE repos

### PR DESCRIPTION
**Pull request by GabeBolton**
I don't know, to me it seems like fewer clicks to get to the introduction and showing the 'accessories' available could increase uptake.

### CODE REVIEW

**Comment by veikman** [comment]
Thank you; I was just looking at doing something like this.

**Comment by GabeBolton** [comment]
> Thank you; I was just looking at doing something like this.


If there is anything else you are thinking of doing, I just finished exams today. While I'm an ultra novice at Clojure and scad, I am really excited about this topography, and I like markdown and bumbling my way through new languages. I'd love help with whatever legwork is needed to get your work either pushed up to tshort or adereth's repo, or more firmly established in it's own right.

**Comment by veikman** [comment]
The most beginner-friendly substantial thing I can think of at the moment is to restore support for the Dactyl-ManuForm’s MCU shelf. Have a look at https://github.com/veikman/dactyl-keyboard/blob/master/config/dactyl_manuform/base.yaml: It’s listed as the first missing feature for upstream parity. It’s the thing that holds the microcontroller PCBA inside the case.

Basically, this task would consist of:

* Grabbing Tom’s model code for the shelf out of the upstream.
* Finding a logical place for it in DMOTE’s modularized package structure.
* Creating a third configuration option for the [MCU support style](https://github.com/veikman/dactyl-keyboard/blob/master/doc/options-main.md#user-content-mcu-support-style) setting.
* Revising the Dactyl-ManuForm YAML configuration file to use the new style.
* Integrating it all so that the shelf ends up in the right place on the Dactyl-ManuForm and is also reasonably easy to use with other designs.
* Testing the result by importing a genuine Dactyl-Manuform from Tom’s STL into the scene with your own DMOTE Dactyl-Manuform build (by editing the SCAD), to see that the shelf does indeed match the original.
* Regenerating the built-in settings documentation so it mentions the new style.

This could end up being a useful tour of the project’s different parts, without having to design really new stuff. Does it sound doable?

https://www.braveclojure.com is a decent place to get oriented with Clojure. The official docs are excellent once you crack the basics.

Editing tips: Unless you’re some dark Emacs god, I highly recommend using Parinfer with your editor to keep Clojure readable; it’s effortless. I use Joker for some basic linting.

**Comment by GabeBolton** [comment]
I've had a look and a bit of a play around, and I think it'll be doable, but I've also just been handed another project. I will try some more over the next few weeks and keep you posted, maybe an issue should be opened to address the points raised for upstream parity.

**Pull request merged**
